---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# excel2eprime

<!-- badges: start -->
<!-- badges: end -->

The goal of excel2eprime is to provide a easy to split experiment sentences by different factors.

## Installation

You can install the development version of excel2eprime from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("wujackwill/excel2eprime")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(excel2eprime)
```

Split experiment materials of different design

```{r split basic}
data <- split_basic("D:\\personal\\excel2eprime\\inst\\basic.xlsx","A")

data
```
```{r split 1 * 2}
data <- split_12("D:\\personal\\excel2eprime\\inst\\12.xlsx","A")

data$con1
```
```{r split 2 * 2}
data <- split_22("D:\\personal\\excel2eprime\\inst\\22.xlsx","A")

data$con1
```



```{r split 2 * 2 * 2}
data <- split_222("D:\\personal\\excel2eprime\\inst\\222.xlsx","A")

data$con1
```
